# Generated by Django 4.0.6 on 2022-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalarticle", "0003_legalarticle_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlehit",
            name="operating_system",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
