# Generated by Django 3.2.14 on 2022-08-22 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("legalarticle", "0012_dislike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dislike",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dislike",
                to="legalarticle.legalarticle",
            ),
        ),
        migrations.AlterField(
            model_name="dislike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dislikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
