# Generated by Django 3.2.14 on 2022-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalarticle", "0014_legalarticle_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalarticle",
            name="_type",
            field=models.CharField(default="sdffd", max_length=125),
            preserve_default=False,
        ),
    ]
