# Generated by Django 3.2.14 on 2022-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legalarticle", "0015_legalarticle__type"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalarticle",
            name="_type2",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="legalarticle",
            name="_type",
            field=models.TextField(blank=True),
        ),
    ]
