# Generated by Django 3.2.14 on 2022-08-30 06:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("legalarticle", "0016_auto_20220829_1154"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalarticle",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
