# Generated by Django 3.2.14 on 2022-09-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalarticle', '0018_alter_legalarticle_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalarticle',
            options={'permissions': (('ایجاد ماده', 'دسترسی به ایجاد ماده'), ('به روزرسانی ماده', 'دسترسی به بروزرسانی ماده'), ('حذف  ماده', 'دسترسی به حذف ماده'))},
        ),
    ]
