# Generated by Django 3.2.14 on 2022-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_guide"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
            ],
        ),
    ]
