# Generated by Django 4.0.6 on 2022-08-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="law",
            name="note",
        ),
    ]
