# Generated by Django 3.2.14 on 2022-08-15 15:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0002_remove_law_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="law",
            name="published",
            field=models.DateField(
                default=datetime.datetime(2022, 8, 15, 15, 2, 43, 525791)
            ),
            preserve_default=False,
        ),
    ]
