# Generated by Django 3.2.14 on 2022-08-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0003_law_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='approval_authority',
            field=models.CharField(default='asd', max_length=125),
            preserve_default=False,
        ),
    ]
