# Generated by Django 3.2.14 on 2022-08-25 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laws", "0005_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to="laws.chapter",
            ),
        ),
    ]
