# Generated by Django 3.2.14 on 2022-09-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_order'),
        ('laws', '0008_auto_20220828_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='categories.category'),
            preserve_default=False,
        ),
    ]
