# Generated by Django 3.2.14 on 2022-09-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_order'),
        ('laws', '0009_alter_law_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='categories.category'),
        ),
    ]
