# Generated by Django 3.2.14 on 2022-08-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='confirmed',
        ),
    ]
